AllCops:
  Exclude:
    - bin/**/*
    - coverage/**/*
  DisplayCopNames: true
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/GuardClause:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - spec/*

Lint/RaiseException:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
