---
language: ruby

services: docker
cache: bundler
rvm:
  - 2.5.5
  - 2.6.3
  - ruby-head

before_install:
  - gem install bundler -v 2.0.0
  - docker pull redislabs/rejson:latest
  - docker run -d -p 6379:6379 redislabs/rejson

install:
  # Install dependency gems
  - bundle install

before_script:
  - bundle install

script:
  - bundle exec rake rubocop
  - bundle exec rspec
