---
language: ruby

services: docker
cache: bundler
rvm:
  - 2.5.5
  - 2.6.3
before_install: gem install bundler -v 2.0.0

install:
  # Install dependency gems
  - bundle install

before_script:
  - bundle install

script:
  - bundle exec rspec